In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Download the ITU dataset
df = pd.read_csv("../data/raw/itu_all_indicators_raw_sample.csv")

In [4]:
df.shape

(376, 15)

In [5]:
df.head()

,SeriesID,SeriesCode,Series,Unit,Database,Year,AreaName,AreaCode,DisaggregationGroup,Disaggregation1,Disaggregation2,Value,Notes,Source,LastModifiedOn
0,9232,HHU4212-%_POP-ISCED01-FEMALE,HH07 - Individuals who used the internet (from...,% of individuals,ITU Households Database,2025,France,FRA,Gender,Primary or less,Female,46.944591,Aged 15 and older,Institut National de la Statistique et des Etu...,2026-06-26
1,8810,HHA4213-%_HH-CHILDREN-,HH06 - Households with Internet access at home...,% of households,ITU Households Database,2025,France,FRA,Family,Children,NaN,98.326201,NaN,Institut National de la Statistique et des Etu...,2026-07-05
2,8816,HHA4213-%_HH-NOCHILDREN-,HH06 - Households with Internet access at home...,% of households,ITU Households Database,2025,France,FRA,Family,No Children,NaN,87.217188,NaN,Institut National de la Statistique et des Etu...,2026-07-05
3,9231,HHU4212-%_POP-ISCED01-,HH07 - Individuals who used the internet (from...,% of individuals,ITU Households Database,2025,France,FRA,Education,Primary or less,NaN,51.695790,Aged 15 and older,Institut National de la Statistique et des Etu...,2026-06-02
4,8812,HHA4213-%_HH-CHILDREN-URBAN,HH06 - Households with Internet access at home...,% of households,ITU Households Database,2025,France,FRA,Location,Children,Urban,97.960964,NaN,Institut National de la Statistique et des Etu...,2026-07-04

In [13]:
df.tail()

,SeriesID,SeriesCode,Series,Unit,Database,Year,AreaName,AreaCode,DisaggregationGroup,Disaggregation1,Disaggregation2,Value,Notes,Source,LastModifiedOn
371,8820,HHA4213-%_HH-URBAN-,HH06 - Households with Internet access at home...,% of households,ITU Households Database,2018,Portugal,PRT,Location,Urban,NaN,84.787920,NaN,Statistics Portugal,2026-07-05
372,8819,HHA4213-%_HH-RURAL-,HH06 - Households with Internet access at home...,% of households,ITU Households Database,2018,Portugal,PRT,Location,Rural,NaN,69.103214,NaN,Statistics Portugal,2024-07-08
373,12047,xHH6_IDI,Estimated proportion of households with Intern...,% of households,ITU World Telecommunication Indicators Database,2018,Singapore,SGP,NaN,NaN,NaN,97.733872,NaN,Infocomm Media Development Authority,2024-01-23
374,12047,xHH6_IDI,Estimated proportion of households with Intern...,% of households,ITU World Telecommunication Indicators Database,2018,Tanzania,TZA,NaN,NaN,NaN,9.112273,NaN,ITU estimate,2021-11-29
375,12047,xHH6_IDI,Estimated proportion of households with Intern...,% of households,ITU World Telecommunication Indicators Database,2018,United States,USA,NaN,NaN,NaN,85.349794,Households with Internet subscription. Does no...,US Census Bureau,2024-01-23

In [14]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SeriesID             376 non-null    int64
 1   SeriesCode           376 non-null    object
 2   Series               376 non-null    object
 3   Unit                 376 non-null    object
 4   Database             376 non-null    object
 5   Year                 376 non-null    int64
 6   AreaName             376 non-null    object
 7   AreaCode             376 non-null    object
 8   DisaggregationGroup  324 non-null    object
 9   Disaggregation1      324 non-null    object
 10  Disaggregation2      188 non-null    object
 11  Value                376 non-null    float64
 12  Notes                47 non-null     object
 13  Source               376 non-null    object
 14  LastModifiedOn       376 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 44.2+ KB

In [12]:
df.columns.tolist()

['SeriesID',
 'SeriesCode',
 'Series',
 'Unit',
 'Database',
 'Year',
 'AreaName',
 'AreaCode',
 'DisaggregationGroup',
 'Disaggregation1',
 'Disaggregation2',
 'Value',
 'Notes',
 'Source',
 'LastModifiedOn']

In [15]:
df["Series"].value_counts()

Series
Estimated proportion of households with Internet access at home                            52
HH06 - Households with Internet access at home - %_HH - CHILDREN                           20
HH06 - Households with Internet access at home - %_HH - NOCHILDREN                         20
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - FEMALE    16
HH06 - Households with Internet access at home - %_HH - RURAL                              16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - MALE      16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - MALE      16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - MALE      16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - FEMALE    16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - FEMALE    16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56             16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - FEMALE     16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2              16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - MALE       16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34             16
HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01             16
HH06 - Households with Internet access at home - %_HH - URBAN                              16
HH06 - Households with Internet access at home - %_HH - NOCHILDREN - RURAL                 15
HH06 - Households with Internet access at home - %_HH - NOCHILDREN - URBAN                 15
HH06 - Households with Internet access at home - %_HH - CHILDREN - RURAL                   15
HH06 - Households with Internet access at home - %_HH - CHILDREN - URBAN                   15
Name: count, dtype: int64

In [16]:
df["Year"].value_counts()

Year
2021    60
2023    51
2024    49
2022    49
2018    48
2019    47
2025    45
2020    27
Name: count, dtype: int64

In [17]:
df["AreaName"].value_counts()

AreaName
Portugal         168
France           148
Singapore         30
United States      9
Ghana              7
Nigeria            7
Tanzania           6
Haiti              1
Name: count, dtype: int64

In [19]:
df.groupby(["AreaName", "Year"]).size()

AreaName       Year
France         2018    21
               2019    21
               2020     1
               2021    21
               2022    21
               2023    21
               2024    21
               2025    21
Ghana          2018     1
               2019     1
               2020     1
               2021     1
               2022     1
               2023     1
               2024     1
Haiti          2018     1
Nigeria        2018     1
               2019     1
               2020     1
               2021     1
               2022     1
               2023     1
               2024     1
Portugal       2018    21
               2019    21
               2020    21
               2021    21
               2022    21
               2023    21
               2024    21
               2025    21
Singapore      2018     1
               2019     1
               2020     1
               2021    15
               2022     3
               2023     3
               2024     3
               2025     3
Tanzania       2018     1
               2019     1
               2020     1
               2022     1
               2023     1
               2024     1
United States  2018     1
               2019     1
               2020     1
               2021     1
               2022     1
               2023     3
               2024     1
dtype: int64

In [20]:
country_year_counts = (df.groupby(["AreaName", "Year"]).size().unstack(fill_value=0).rename(columns=lambda x: f"Year_{x}"))

In [21]:
country_year_counts

Year,Year_2018,Year_2019,Year_2020,Year_2021,Year_2022,Year_2023,Year_2024,Year_2025
AreaName,,,,,,,,
France,21,21,1,21,21,21,21,21
Ghana,1,1,1,1,1,1,1,0
Haiti,1,0,0,0,0,0,0,0
Nigeria,1,1,1,1,1,1,1,0
Portugal,21,21,21,21,21,21,21,21
Singapore,1,1,1,15,3,3,3,3
Tanzania,1,1,1,0,1,1,1,0
United States,1,1,1,1,1,3,1,0

In [24]:
france_2018 = df[(df["AreaName"] == "France") & (df["Year"] == 2018)]

france_2018[["Series", "DisaggregationGroup", "Disaggregation1", "Disaggregation2"]]

,Series,DisaggregationGroup,Disaggregation1,Disaggregation2
328,Estimated proportion of households with Intern...,NaN,NaN,NaN
329,HH06 - Households with Internet access at home...,Location,Urban,NaN
330,HH06 - Households with Internet access at home...,Location,Rural,NaN
331,HH07 - Individuals who used the internet (from...,Gender,Primary or less,Female
332,HH06 - Households with Internet access at home...,Location,No Children,Urban
333,HH07 - Individuals who used the internet (from...,Gender,Lower secondary,Female
334,HH06 - Households with Internet access at home...,Location,No Children,Rural
335,HH07 - Individuals who used the internet (from...,Education,Tertiary education,NaN
336,HH06 - Households with Internet access at home...,Location,Children,Urban
337,HH07 - Individuals who used the internet (from...,Gender,Tertiary education,Male
338,HH07 - Individuals who used the internet (from...,Education,Upper secondary,NaN
339,HH07 - Individuals who used the internet (from...,Education,Primary or less,NaN
340,HH06 - Households with Internet access at home...,Family,No Children,NaN
341,HH07 - Individuals who used the internet (from...,Education,Lower secondary,NaN
342,HH06 - Households with Internet access at home...,Family,Children,NaN
343,HH07 - Individuals who used the internet (from...,Gender,Primary or less,Male
344,HH07 - Individuals who used the internet (from...,Gender,Lower secondary,Male
345,HH07 - Individuals who used the internet (from...,Gender,Upper secondary,Female
346,HH06 - Households with Internet access at home...,Location,Children,Rural
347,HH07 - Individuals who used the internet (from...,Gender,Upper secondary,Male
348,HH07 - Individuals who used the internet (from...,Gender,Tertiary education,Female

In [25]:
ghana_2018 = df[(df["AreaName"] == "Ghana") & (df["Year"] == 2018)]

ghana_2018[["Series", "DisaggregationGroup", "Disaggregation1", "Disaggregation2"]]

,Series,DisaggregationGroup,Disaggregation1,Disaggregation2
349,Estimated proportion of households with Intern...,NaN,NaN,NaN

In [26]:
df["Series"].unique()

array(['HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - FEMALE',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - FEMALE',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - MALE',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - RURAL',
       'Estimated proportion of households with Internet access at home',
       'HH06 - Households with Internet access at home - %_HH - RURAL',
       'HH06 - Households with Internet access at home - %_HH - URBAN'],
      dtype=object)

In [33]:
df["SeriesCode"].unique().tolist()

['HHU4212-%_POP-ISCED01-FEMALE',
 'HHA4213-%_HH-CHILDREN-',
 'HHA4213-%_HH-NOCHILDREN-',
 'HHU4212-%_POP-ISCED01-',
 'HHA4213-%_HH-CHILDREN-URBAN',
 'HHU4212-%_POP-ISCED34-',
 'HHU4212-%_POP-ISCED2-MALE',
 'HHU4212-%_POP-ISCED2-',
 'HHU4212-%_POP-ISCED2-FEMALE',
 'HHA4213-%_HH-NOCHILDREN-URBAN',
 'HHU4212-%_POP-ISCED56-',
 'HHA4213-%_HH-NOCHILDREN-RURAL',
 'HHU4212-%_POP-ISCED34-FEMALE',
 'HHU4212-%_POP-ISCED56-FEMALE',
 'HHU4212-%_POP-ISCED01-MALE',
 'HHU4212-%_POP-ISCED34-MALE',
 'HHU4212-%_POP-ISCED56-MALE',
 'HHA4213-%_HH-CHILDREN-RURAL',
 'xHH6_IDI',
 'HHA4213-%_HH-RURAL-',
 'HHA4213-%_HH-URBAN-']

In [38]:
france_2021 = df[(df["AreaName"] =="France") & (df["Year"] == 2021)]

france_2021[["SeriesCode", "Series","SeriesID","Value", "DisaggregationGroup", "Disaggregation1", "Disaggregation2"]]

,SeriesCode,Series,SeriesID,Value,DisaggregationGroup,Disaggregation1,Disaggregation2
194,xHH6_IDI,Estimated proportion of households with Intern...,12047,87.233657,NaN,NaN,NaN
195,HHA4213-%_HH-CHILDREN-RURAL,HH06 - Households with Internet access at home...,8811,98.670996,Location,Children,Rural
196,HHU4212-%_POP-ISCED34-FEMALE,HH07 - Individuals who used the internet (from...,9238,89.833953,Gender,Upper secondary,Female
197,HHU4212-%_POP-ISCED01-FEMALE,HH07 - Individuals who used the internet (from...,9232,43.807899,Gender,Primary or less,Female
198,HHA4213-%_HH-NOCHILDREN-RURAL,HH06 - Households with Internet access at home...,8817,80.342862,Location,No Children,Rural
199,HHA4213-%_HH-CHILDREN-,HH06 - Households with Internet access at home...,8810,98.882257,Family,Children,NaN
200,HHU4212-%_POP-ISCED01-,HH07 - Individuals who used the internet (from...,9231,47.471834,Education,Primary or less,NaN
201,HHU4212-%_POP-ISCED2-,HH07 - Individuals who used the internet (from...,9234,88.995369,Education,Lower secondary,NaN
202,HHU4212-%_POP-ISCED34-MALE,HH07 - Individuals who used the internet (from...,9239,88.203022,Gender,Upper secondary,Male
203,HHU4212-%_POP-ISCED34-,HH07 - Individuals who used the internet (from...,9237,88.993935,Education,Upper secondary,NaN
204,HHU4212-%_POP-ISCED01-MALE,HH07 - Individuals who used the internet (from...,9233,51.941143,Gender,Primary or less,Male
205,HHU4212-%_POP-ISCED56-,HH07 - Individuals who used the internet (from...,9240,96.985876,Education,Tertiary education,NaN
206,HHA4213-%_HH-NOCHILDREN-,HH06 - Households with Internet access at home...,8816,83.675336,Family,No Children,NaN
207,HHU4212-%_POP-ISCED56-MALE,HH07 - Individuals who used the internet (from...,9242,96.691532,Gender,Tertiary education,Male
208,HHU4212-%_POP-ISCED56-FEMALE,HH07 - Individuals who used the internet (from...,9241,97.232321,Gender,Tertiary education,Female
209,HHA4213-%_HH-CHILDREN-URBAN,HH06 - Households with Internet access at home...,8812,98.944524,Location,Children,Urban
210,HHU4212-%_POP-ISCED2-MALE,HH07 - Individuals who used the internet (from...,9236,91.039600,Gender,Lower secondary,Male
211,HHA4213-%_HH-NOCHILDREN-URBAN,HH06 - Households with Internet access at home...,8818,84.563658,Location,No Children,Urban
212,HHU4212-%_POP-ISCED2-FEMALE,HH07 - Individuals who used the internet (from...,9235,87.308252,Gender,Lower secondary,Female
213,HHA4213-%_HH-URBAN-,HH06 - Households with Internet access at home...,8820,87.872311,Location,Urban,NaN
214,HHA4213-%_HH-RURAL-,HH06 - Households with Internet access at home...,8819,84.894659,Location,Rural,NaN