# Country Selection

## Purpose
The purpose of this notebook is to map out the parameters for which I will use as a guideline to select the countries for this analysis.

The World Bank income classifications are used to establish the initial candidate pool. Selected countries will be evauluated based on geographic diversity
and the ITU data availability before the final sample is selected.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
## Download World Bank Dataset

df = pd.read_csv("../data/raw/nations_incomes_2026_07_15.csv")

In [ ]:
## Reviewing the head of the dataframe
df.head()

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN

In [8]:
df.shape

(268, 5)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Economy           265 non-null    object
 1   Code              265 non-null    object
 2   Region            218 non-null    object
 3   Income group      218 non-null    object
 4   Lending category  145 non-null    object
dtypes: object(5)
memory usage: 10.6+ KB

In [10]:
df["Income group"].value_counts()

Income group
High income            87
Upper middle income    59
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [11]:
df["Income group"].value_counts(dropna=False)

Income group
High income            87
Upper middle income    59
NaN                    50
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [12]:
df[df["Income group"].isna()]

,Economy,Code,Region,Income group,Lending category
218,NaN,NaN,NaN,NaN,NaN
219,Africa Eastern and Southern,AFE,NaN,NaN,NaN
220,Africa Western and Central,AFW,NaN,NaN,NaN
221,Arab World,ARB,NaN,NaN,NaN
222,Caribbean small states,CSS,NaN,NaN,NaN
223,Central Europe and the Baltics,CEB,NaN,NaN,NaN
224,Early-demographic dividend,EAR,NaN,NaN,NaN
225,East Asia & Pacific,EAS,NaN,NaN,NaN
226,East Asia & Pacific (excluding high income),EAP,NaN,NaN,NaN
227,East Asia & Pacific (IDA & IBRD),TEA,NaN,NaN,NaN
228,Euro area,EMU,NaN,NaN,NaN
229,Europe & Central Asia,ECS,NaN,NaN,NaN
230,Europe & Central Asia (excluding high income),ECA,NaN,NaN,NaN
231,Europe & Central Asia (IDA & IBRD),TEC,NaN,NaN,NaN
232,European Union,EUU,NaN,NaN,NaN
233,Heavily indebted poor countries (HIPC),HPC,NaN,NaN,NaN
234,High income,HIC,NaN,NaN,NaN
235,IBRD only,IBD,NaN,NaN,NaN
236,IDA & IBRD total,IBT,NaN,NaN,NaN
237,IDA blend,IDB,NaN,NaN,NaN
238,IDA only,IDX,NaN,NaN,NaN
239,IDA total,IDA,NaN,NaN,NaN
240,Late-demographic dividend,LTE,NaN,NaN,NaN
241,Latin America & Caribbean,LCN,NaN,NaN,NaN
242,Latin America & Caribbean (excluding high income),LAC,NaN,NaN,NaN
243,Latin America & Caribbean (IDA & IBRD),TLA,NaN,NaN,NaN
244,Least developed countries: UN classification,LDC,NaN,NaN,NaN
245,Low & middle income,LMY,NaN,NaN,NaN
246,Low income,LIC,NaN,NaN,NaN
247,Lower middle income,LMC,NaN,NaN,NaN
248,"Middle East, North Africa, Afghanistan and Pak...",MEA,NaN,NaN,NaN
249,"Middle East, North Africa, Afghanistan and Pak...",MNA,NaN,NaN,NaN
250,"Middle East, North Africa, Afghanistan and Pak...",TMN,NaN,NaN,NaN
251,Middle income,MIC,NaN,NaN,NaN
252,North America,NAC,NaN,NaN,NaN
253,OECD members,OED,NaN,NaN,NaN
254,Other small states,OSS,NaN,NaN,NaN
255,Pacific island small states,PSS,NaN,NaN,NaN
256,Post-demographic dividend,PST,NaN,NaN,NaN
257,Pre-demographic dividend,PRE,NaN,NaN,NaN
258,Small states,SST,NaN,NaN,NaN
259,South Asia,SAS,NaN,NaN,NaN
260,South Asia (IDA & IBRD),TSA,NaN,NaN,NaN
261,Sub-Saharan Africa,SSF,NaN,NaN,NaN
262,Sub-Saharan Africa (excluding high income),SSA,NaN,NaN,NaN
263,Sub-Saharan Africa (IDA & IBRD),TSS,NaN,NaN,NaN
264,Upper middle income,UMC,NaN,NaN,NaN
265,World,WLD,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN

In [13]:
# Creating New dataframe to filter econimies

## This dataset contains both individual economies and aggregated groups such as regions, income gaps etc. The aggregated records contain the income classification
## that is needed to conduct this analysis and there are not included. All records with a non-null have been retained to creat the candidate economy dataset.

In [14]:
countries = df[df["Income group"].notna()].copy()

In [15]:
countries.shape

(218, 5)

In [17]:
countries.isna().sum()

Economy              0
Code                 0
Region               0
Income group         0
Lending category    73
dtype: int64

In [19]:
countries["Region"].value_counts()

Region
Europe & Central Asia                                58
Sub-Saharan Africa                                   48
Latin America & Caribbean                            42
East Asia & Pacific                                  38
Middle East, North Africa, Afghanistan & Pakistan    23
South Asia                                            6
North America                                         3
Name: count, dtype: int64

In [27]:
SSA = countries[countries["Region"] == "Sub-Saharan Africa"]

In [28]:
SSA.shape

(48, 5)

In [30]:
SSA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, 5 to 217
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Economy           48 non-null     object
 1   Code              48 non-null     object
 2   Region            48 non-null     object
 3   Income group      48 non-null     object
 4   Lending category  48 non-null     object
dtypes: object(5)
memory usage: 2.2+ KB

In [31]:
SSA_list = SSA["Economy"].tolist()

In [34]:
SSA_list

['Angola',
 'Benin',
 'Botswana',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Côte d’Ivoire',
 'Equatorial Guinea',
 'Eritrea',
 'Eswatini',
 'Ethiopia',
 'Gabon',
 'Gambia, The',
 'Ghana',
 'Guinea',
 'Guinea-Bissau',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Madagascar',
 'Malawi',
 'Mali',
 'Mauritania',
 'Mauritius',
 'Mozambique',
 'Namibia',
 'Niger',
 'Nigeria',
 'Rwanda',
 'São Tomé and Príncipe',
 'Senegal',
 'Seychelles',
 'Sierra Leone',
 'Somalia, Fed. Rep.',
 'South Africa',
 'South Sudan',
 'Sudan',
 'Tanzania',
 'Togo',
 'Uganda',
 'Zambia',
 'Zimbabwe']

In [38]:
countries["Income group"].value_counts()

Income group
High income            87
Upper middle income    59
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [39]:
high_income = countries[countries["Income group"] == "High income"]

high_income

,Economy,Code,Region,Income group,Lending category
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN
6,Antigua and Barbuda,ATG,Latin America & Caribbean,High income,IBRD
9,Aruba,ABW,Latin America & Caribbean,High income,NaN
10,Australia,AUS,East Asia & Pacific,High income,NaN
...,...,...,...,...,...
205,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",High income,NaN
206,United Kingdom,GBR,Europe & Central Asia,High income,NaN
207,United States,USA,North America,High income,NaN
208,Uruguay,URY,Latin America & Caribbean,High income,IBRD
213,Virgin Islands (U.S.),VIR,Latin America & Caribbean,High income,NaN

In [42]:
upper_middle_income = countries[countries["Income group"] == "Upper middle income"]

upper_middle_income

,Economy,Code,Region,Income group,Lending category
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
7,Argentina,ARG,Latin America & Caribbean,Upper middle income,IBRD
8,Armenia,ARM,Europe & Central Asia,Upper middle income,IBRD
12,Azerbaijan,AZE,Europe & Central Asia,Upper middle income,IBRD
17,Belarus,BLR,Europe & Central Asia,Upper middle income,IBRD
19,Belize,BLZ,Latin America & Caribbean,Upper middle income,Blend
24,Bosnia and Herzegovina,BIH,Europe & Central Asia,Upper middle income,IBRD
25,Botswana,BWA,Sub-Saharan Africa,Upper middle income,IBRD
26,Brazil,BRA,Latin America & Caribbean,Upper middle income,IBRD
32,Cabo Verde,CPV,Sub-Saharan Africa,Upper middle income,Blend
41,China,CHN,East Asia & Pacific,Upper middle income,IBRD
42,Colombia,COL,Latin America & Caribbean,Upper middle income,IBRD
49,Cuba,CUB,Latin America & Caribbean,Upper middle income,NaN
55,Dominica,DMA,Latin America & Caribbean,Upper middle income,Blend
56,Dominican Republic,DOM,Latin America & Caribbean,Upper middle income,IBRD
57,Ecuador,ECU,Latin America & Caribbean,Upper middle income,IBRD
59,El Salvador,SLV,Latin America & Caribbean,Upper middle income,IBRD
60,Equatorial Guinea,GNQ,Sub-Saharan Africa,Upper middle income,IBRD
66,Fiji,FJI,East Asia & Pacific,Upper middle income,Blend
70,Gabon,GAB,Sub-Saharan Africa,Upper middle income,IBRD
72,Georgia,GEO,Europe & Central Asia,Upper middle income,IBRD
78,Grenada,GRD,Latin America & Caribbean,Upper middle income,Blend
80,Guatemala,GTM,Latin America & Caribbean,Upper middle income,IBRD
90,Indonesia,IDN,East Asia & Pacific,Upper middle income,IBRD
91,"Iran, Islamic Rep.",IRN,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
92,Iraq,IRQ,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
97,Jamaica,JAM,Latin America & Caribbean,Upper middle income,IBRD
99,Jordan,JOR,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
100,Kazakhstan,KAZ,Europe & Central Asia,Upper middle income,IBRD
105,Kosovo,XKX,Europe & Central Asia,Upper middle income,IDA
113,Libya,LBY,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
120,Malaysia,MYS,East Asia & Pacific,Upper middle income,IBRD
121,Maldives,MDV,South Asia,Upper middle income,IDA
124,Marshall Islands,MHL,East Asia & Pacific,Upper middle income,IDA
126,Mauritius,MUS,Sub-Saharan Africa,Upper middle income,IBRD
127,Mexico,MEX,Latin America & Caribbean,Upper middle income,IBRD
128,"Micronesia, Fed. Sts.",FSM,East Asia & Pacific,Upper middle income,IDA
129,Moldova,MDA,Europe & Central Asia,Upper middle income,IBRD
131,Mongolia,MNG,East Asia & Pacific,Upper middle income,IBRD
132,Montenegro,MNE,Europe & Central Asia,Upper middle income,IBRD
145,North Macedonia,MKD,Europe & Central Asia,Upper middle income,IBRD
153,Paraguay,PRY,Latin America & Caribbean,Upper middle income,IBRD
154,Peru,PER,Latin America & Caribbean,Upper middle income,IBRD
155,Philippines,PHL,East Asia & Pacific,Upper middle income,IBRD
163,Samoa,WSM,East Asia & Pacific,Upper middle income,IDA
168,Serbia,SRB,Europe & Central Asia,Upper middle income,IBRD
177,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,IBRD
180,Sri Lanka,LKA,South Asia,Upper middle income,IDA
182,St. Lucia,LCA,Latin America & Caribbean,Upper middle income,Blend
184,St. Vincent and the Grenadines,VCT,Latin America & Caribbean,Upper middle income,Blend
186,Suriname,SUR,Latin America & Caribbean,Upper middle income,Blend
193,Thailand,THA,East Asia & Pacific,Upper middle income,IBRD
196,Tonga,TON,East Asia & Pacific,Upper middle income,IDA
199,Türkiye,TUR,Europe & Central Asia,Upper middle income,IBRD
200,Turkmenistan,TKM,Europe & Central Asia,Upper middle income,IBRD
202,Tuvalu,TUV,East Asia & Pacific,Upper middle income,IDA
204,Ukraine,UKR,Europe & Central Asia,Upper middle income,IBRD
212,Viet Nam,VNM,East Asia & Pacific,Upper middle income,IBRD

In [43]:
lower_middle_income = countries[countries["Income group"] == "Lower middle income"]

lower_middle_income

,Economy,Code,Region,Income group,Lending category
5,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD
15,Bangladesh,BGD,South Asia,Lower middle income,IDA
20,Benin,BEN,Sub-Saharan Africa,Lower middle income,IDA
22,Bhutan,BTN,South Asia,Lower middle income,IDA
23,Bolivia,BOL,Latin America & Caribbean,Lower middle income,IBRD
33,Cambodia,KHM,East Asia & Pacific,Lower middle income,IDA
34,Cameroon,CMR,Sub-Saharan Africa,Lower middle income,Blend
43,Comoros,COM,Sub-Saharan Africa,Lower middle income,IDA
45,"Congo, Rep.",COG,Sub-Saharan Africa,Lower middle income,Blend
47,Côte d’Ivoire,CIV,Sub-Saharan Africa,Lower middle income,Blend
54,Djibouti,DJI,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IDA
58,"Egypt, Arab Rep.",EGY,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
63,Eswatini,SWZ,Sub-Saharan Africa,Lower middle income,Blend
74,Ghana,GHA,Sub-Saharan Africa,Lower middle income,IDA
81,Guinea,GIN,Sub-Saharan Africa,Lower middle income,IDA
84,Haiti,HTI,Latin America & Caribbean,Lower middle income,IDA
85,Honduras,HND,Latin America & Caribbean,Lower middle income,IDA
89,India,IND,South Asia,Lower middle income,IBRD
101,Kenya,KEN,Sub-Saharan Africa,Lower middle income,Blend
102,Kiribati,KIR,East Asia & Pacific,Lower middle income,IDA
107,Kyrgyz Republic,KGZ,Europe & Central Asia,Lower middle income,IDA
108,Lao PDR,LAO,East Asia & Pacific,Lower middle income,IDA
110,Lebanon,LBN,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
111,Lesotho,LSO,Sub-Saharan Africa,Lower middle income,IDA
125,Mauritania,MRT,Sub-Saharan Africa,Lower middle income,IDA
133,Morocco,MAR,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
135,Myanmar,MMR,East Asia & Pacific,Lower middle income,IDA
136,Namibia,NAM,Sub-Saharan Africa,Lower middle income,IBRD
138,Nepal,NPL,South Asia,Lower middle income,IDA
142,Nicaragua,NIC,Latin America & Caribbean,Lower middle income,IDA
144,Nigeria,NGA,Sub-Saharan Africa,Lower middle income,Blend
149,Pakistan,PAK,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Blend
152,Papua New Guinea,PNG,East Asia & Pacific,Lower middle income,Blend
165,São Tomé and Príncipe,STP,Sub-Saharan Africa,Lower middle income,IDA
167,Senegal,SEN,Sub-Saharan Africa,Lower middle income,IDA
175,Solomon Islands,SLB,East Asia & Pacific,Lower middle income,IDA
191,Tajikistan,TJK,Europe & Central Asia,Lower middle income,IDA
192,Tanzania,TZA,Sub-Saharan Africa,Lower middle income,IDA
194,Timor-Leste,TLS,East Asia & Pacific,Lower middle income,Blend
195,Togo,TGO,Sub-Saharan Africa,Lower middle income,IDA
198,Tunisia,TUN,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
209,Uzbekistan,UZB,Europe & Central Asia,Lower middle income,Blend
210,Vanuatu,VUT,East Asia & Pacific,Lower middle income,IDA
211,"Venezuela, RB",VEN,Latin America & Caribbean,Lower middle income,IBRD
214,West Bank and Gaza,PSE,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,NaN
216,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,IDA
217,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,Blend

In [46]:
lower_income = countries[countries["Income group"] == "Low income"]

lower_income

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
30,Burkina Faso,BFA,Sub-Saharan Africa,Low income,IDA
31,Burundi,BDI,Sub-Saharan Africa,Low income,IDA
37,Central African Republic,CAF,Sub-Saharan Africa,Low income,IDA
38,Chad,TCD,Sub-Saharan Africa,Low income,IDA
44,"Congo, Dem. Rep.",COD,Sub-Saharan Africa,Low income,IDA
61,Eritrea,ERI,Sub-Saharan Africa,Low income,IDA
64,Ethiopia,ETH,Sub-Saharan Africa,Low income,IDA
71,"Gambia, The",GMB,Sub-Saharan Africa,Low income,IDA
82,Guinea-Bissau,GNB,Sub-Saharan Africa,Low income,IDA
103,"Korea, Dem. People's Rep.",PRK,East Asia & Pacific,Low income,NaN
112,Liberia,LBR,Sub-Saharan Africa,Low income,IDA
118,Madagascar,MDG,Sub-Saharan Africa,Low income,IDA
119,Malawi,MWI,Sub-Saharan Africa,Low income,IDA
122,Mali,MLI,Sub-Saharan Africa,Low income,IDA
134,Mozambique,MOZ,Sub-Saharan Africa,Low income,IDA
143,Niger,NER,Sub-Saharan Africa,Low income,IDA
162,Rwanda,RWA,Sub-Saharan Africa,Low income,IDA
170,Sierra Leone,SLE,Sub-Saharan Africa,Low income,IDA
176,"Somalia, Fed. Rep.",SOM,Sub-Saharan Africa,Low income,IDA
178,South Sudan,SSD,Sub-Saharan Africa,Low income,IDA
185,Sudan,SDN,Sub-Saharan Africa,Low income,IDA
189,Syrian Arab Republic,SYR,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
203,Uganda,UGA,Sub-Saharan Africa,Low income,IDA
215,"Yemen, Rep.",YEM,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA

In [ ]:
## Converted the separate income lists into their own groups. How I will filter on the countries from that income group & what region they are in 

countries["Region"].unique()

array(['Middle East, North Africa, Afghanistan & Pakistan',
       'Europe & Central Asia', 'East Asia & Pacific',
       'Sub-Saharan Africa', 'Latin America & Caribbean', 'South Asia',
       'North America'], dtype=object)

In [50]:
upper_middle_income_SSA = countries[(countries["Region"] == "Sub-Saharan Africa") & (countries["Income group"] == "Upper middle income")]

upper_middle_income_SSA

,Economy,Code,Region,Income group,Lending category
25,Botswana,BWA,Sub-Saharan Africa,Upper middle income,IBRD
32,Cabo Verde,CPV,Sub-Saharan Africa,Upper middle income,Blend
60,Equatorial Guinea,GNQ,Sub-Saharan Africa,Upper middle income,IBRD
70,Gabon,GAB,Sub-Saharan Africa,Upper middle income,IBRD
126,Mauritius,MUS,Sub-Saharan Africa,Upper middle income,IBRD
177,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,IBRD

In [51]:
region_income = pd.crosstab( countries["Region"], countries["Income group"])

region_income

Income group,High income,Low income,Lower middle income,Upper middle income
Region,,,,
East Asia & Pacific,16,1,8,13
Europe & Central Asia,40,0,3,15
Latin America & Caribbean,19,0,5,18
"Middle East, North Africa, Afghanistan & Pakistan",8,3,7,5
North America,3,0,0,0
South Asia,0,0,4,2
Sub-Saharan Africa,1,21,20,6

In [52]:
candidate_pool = countries.sort_values(by=["Income group", "Region", "Economy"])

candidate_pool

,Economy,Code,Region,Income group,Lending category
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
10,Australia,AUS,East Asia & Pacific,High income,NaN
28,Brunei Darussalam,BRN,East Asia & Pacific,High income,NaN
69,French Polynesia,PYF,East Asia & Pacific,High income,NaN
79,Guam,GUM,East Asia & Pacific,High income,NaN
...,...,...,...,...,...
32,Cabo Verde,CPV,Sub-Saharan Africa,Upper middle income,Blend
60,Equatorial Guinea,GNQ,Sub-Saharan Africa,Upper middle income,IBRD
70,Gabon,GAB,Sub-Saharan Africa,Upper middle income,IBRD
126,Mauritius,MUS,Sub-Saharan Africa,Upper middle income,IBRD
177,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,IBRD

In [ ]:
candidate_pool[["Economy", "Income group", "Code", "Region"]]

               Economy         Income group Code               Region
3       American Samoa          High income  ASM  East Asia & Pacific
10           Australia          High income  AUS  East Asia & Pacific
28   Brunei Darussalam          High income  BRN  East Asia & Pacific
69    French Polynesia          High income  PYF  East Asia & Pacific
79                Guam          High income  GUM  East Asia & Pacific
..                 ...                  ...  ...                  ...
32          Cabo Verde  Upper middle income  CPV   Sub-Saharan Africa
60   Equatorial Guinea  Upper middle income  GNQ   Sub-Saharan Africa
70               Gabon  Upper middle income  GAB   Sub-Saharan Africa
126          Mauritius  Upper middle income  MUS   Sub-Saharan Africa
177       South Africa  Upper middle income  ZAF   Sub-Saharan Africa

[218 rows x 4 columns]

In [55]:
## Creating a list so incomes are from low -> high

income_order = ['Low income', 'Lower middle income', 'Upper middle income', 'High income']

In [56]:
countries["Income group"] = pd.Categorical(
    countries['Income group'],
    categories=income_order,
    ordered=True
)

In [58]:
candidate_pool = countries.sort_values(by= ['Income group', 'Region', 'Economy'])

In [59]:
candidate_pool

,Economy,Code,Region,Income group,Lending category
103,"Korea, Dem. People's Rep.",PRK,East Asia & Pacific,Low income,NaN
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
189,Syrian Arab Republic,SYR,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
215,"Yemen, Rep.",YEM,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
30,Burkina Faso,BFA,Sub-Saharan Africa,Low income,IDA
...,...,...,...,...,...
205,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",High income,NaN
21,Bermuda,BMU,North America,High income,NaN
35,Canada,CAN,North America,High income,NaN
207,United States,USA,North America,High income,NaN
169,Seychelles,SYC,Sub-Saharan Africa,High income,IBRD

In [60]:
candidate_pool.sort_values(by=["Economy", 'Code', 'Region','Income group'])

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN
...,...,...,...,...,...
213,Virgin Islands (U.S.),VIR,Latin America & Caribbean,High income,NaN
214,West Bank and Gaza,PSE,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,NaN
215,"Yemen, Rep.",YEM,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
216,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,IDA
217,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,Blend

In [81]:
#Low income

# Sort through the columns I want
candidate_pool [ candidate_pool["Income group"] == "Low income"].sort_values(by=['Region','Economy'])[['Economy','Region','Income group','Code']]

,Economy,Region,Income group,Code
103,"Korea, Dem. People's Rep.",East Asia & Pacific,Low income,PRK
0,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,AFG
189,Syrian Arab Republic,"Middle East, North Africa, Afghanistan & Pakistan",Low income,SYR
215,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,YEM
30,Burkina Faso,Sub-Saharan Africa,Low income,BFA
31,Burundi,Sub-Saharan Africa,Low income,BDI
37,Central African Republic,Sub-Saharan Africa,Low income,CAF
38,Chad,Sub-Saharan Africa,Low income,TCD
44,"Congo, Dem. Rep.",Sub-Saharan Africa,Low income,COD
61,Eritrea,Sub-Saharan Africa,Low income,ERI
64,Ethiopia,Sub-Saharan Africa,Low income,ETH
71,"Gambia, The",Sub-Saharan Africa,Low income,GMB
82,Guinea-Bissau,Sub-Saharan Africa,Low income,GNB
112,Liberia,Sub-Saharan Africa,Low income,LBR
118,Madagascar,Sub-Saharan Africa,Low income,MDG
119,Malawi,Sub-Saharan Africa,Low income,MWI
122,Mali,Sub-Saharan Africa,Low income,MLI
134,Mozambique,Sub-Saharan Africa,Low income,MOZ
143,Niger,Sub-Saharan Africa,Low income,NER
162,Rwanda,Sub-Saharan Africa,Low income,RWA
170,Sierra Leone,Sub-Saharan Africa,Low income,SLE
176,"Somalia, Fed. Rep.",Sub-Saharan Africa,Low income,SOM
178,South Sudan,Sub-Saharan Africa,Low income,SSD
185,Sudan,Sub-Saharan Africa,Low income,SDN
203,Uganda,Sub-Saharan Africa,Low income,UGA

In [ ]:
##Lower Middle income

candidate_pool [candidate_pool['Income group'] == 'Lower middle income'].sort_values(by=['Region','Economy'])[['Region','Income group', 'Economy','Code']]

## Countries selected:Kenya, Angola, India, Cambodia, Morocco, Honduras, Kyrgyz Republic, Papua New Guinea

,Region,Income group,Economy,Code
33,East Asia & Pacific,Lower middle income,Cambodia,KHM
102,East Asia & Pacific,Lower middle income,Kiribati,KIR
108,East Asia & Pacific,Lower middle income,Lao PDR,LAO
135,East Asia & Pacific,Lower middle income,Myanmar,MMR
152,East Asia & Pacific,Lower middle income,Papua New Guinea,PNG
175,East Asia & Pacific,Lower middle income,Solomon Islands,SLB
194,East Asia & Pacific,Lower middle income,Timor-Leste,TLS
210,East Asia & Pacific,Lower middle income,Vanuatu,VUT
107,Europe & Central Asia,Lower middle income,Kyrgyz Republic,KGZ
191,Europe & Central Asia,Lower middle income,Tajikistan,TJK
209,Europe & Central Asia,Lower middle income,Uzbekistan,UZB
23,Latin America & Caribbean,Lower middle income,Bolivia,BOL
84,Latin America & Caribbean,Lower middle income,Haiti,HTI
85,Latin America & Caribbean,Lower middle income,Honduras,HND
142,Latin America & Caribbean,Lower middle income,Nicaragua,NIC
211,Latin America & Caribbean,Lower middle income,"Venezuela, RB",VEN
54,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Djibouti,DJI
58,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,"Egypt, Arab Rep.",EGY
110,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Lebanon,LBN
133,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Morocco,MAR
149,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Pakistan,PAK
198,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Tunisia,TUN
214,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,West Bank and Gaza,PSE
15,South Asia,Lower middle income,Bangladesh,BGD
22,South Asia,Lower middle income,Bhutan,BTN
89,South Asia,Lower middle income,India,IND
138,South Asia,Lower middle income,Nepal,NPL
5,Sub-Saharan Africa,Lower middle income,Angola,AGO
20,Sub-Saharan Africa,Lower middle income,Benin,BEN
34,Sub-Saharan Africa,Lower middle income,Cameroon,CMR
43,Sub-Saharan Africa,Lower middle income,Comoros,COM
45,Sub-Saharan Africa,Lower middle income,"Congo, Rep.",COG
47,Sub-Saharan Africa,Lower middle income,Côte d’Ivoire,CIV
63,Sub-Saharan Africa,Lower middle income,Eswatini,SWZ
74,Sub-Saharan Africa,Lower middle income,Ghana,GHA
81,Sub-Saharan Africa,Lower middle income,Guinea,GIN
101,Sub-Saharan Africa,Lower middle income,Kenya,KEN
111,Sub-Saharan Africa,Lower middle income,Lesotho,LSO
125,Sub-Saharan Africa,Lower middle income,Mauritania,MRT
136,Sub-Saharan Africa,Lower middle income,Namibia,NAM
144,Sub-Saharan Africa,Lower middle income,Nigeria,NGA
167,Sub-Saharan Africa,Lower middle income,Senegal,SEN
165,Sub-Saharan Africa,Lower middle income,São Tomé and Príncipe,STP
192,Sub-Saharan Africa,Lower middle income,Tanzania,TZA
195,Sub-Saharan Africa,Lower middle income,Togo,TGO
216,Sub-Saharan Africa,Lower middle income,Zambia,ZMB
217,Sub-Saharan Africa,Lower middle income,Zimbabwe,ZWE

In [ ]:
# Upper Middle income

candidate_pool [ candidate_pool['Income group'] == 'Upper middle income'].sort_values(by=['Region','Economy'])[['Region','Income group', 'Economy','Code']]

# Countries selected: Colombia, Jamaica, Armenia, Ukraine, Indonesia, Samoa, Iraq, Botswana

,Region,Income group,Economy,Code
41,East Asia & Pacific,Upper middle income,China,CHN
66,East Asia & Pacific,Upper middle income,Fiji,FJI
90,East Asia & Pacific,Upper middle income,Indonesia,IDN
120,East Asia & Pacific,Upper middle income,Malaysia,MYS
124,East Asia & Pacific,Upper middle income,Marshall Islands,MHL
128,East Asia & Pacific,Upper middle income,"Micronesia, Fed. Sts.",FSM
131,East Asia & Pacific,Upper middle income,Mongolia,MNG
155,East Asia & Pacific,Upper middle income,Philippines,PHL
163,East Asia & Pacific,Upper middle income,Samoa,WSM
193,East Asia & Pacific,Upper middle income,Thailand,THA
196,East Asia & Pacific,Upper middle income,Tonga,TON
202,East Asia & Pacific,Upper middle income,Tuvalu,TUV
212,East Asia & Pacific,Upper middle income,Viet Nam,VNM
1,Europe & Central Asia,Upper middle income,Albania,ALB
8,Europe & Central Asia,Upper middle income,Armenia,ARM
12,Europe & Central Asia,Upper middle income,Azerbaijan,AZE
17,Europe & Central Asia,Upper middle income,Belarus,BLR
24,Europe & Central Asia,Upper middle income,Bosnia and Herzegovina,BIH
72,Europe & Central Asia,Upper middle income,Georgia,GEO
100,Europe & Central Asia,Upper middle income,Kazakhstan,KAZ
105,Europe & Central Asia,Upper middle income,Kosovo,XKX
129,Europe & Central Asia,Upper middle income,Moldova,MDA
132,Europe & Central Asia,Upper middle income,Montenegro,MNE
145,Europe & Central Asia,Upper middle income,North Macedonia,MKD
168,Europe & Central Asia,Upper middle income,Serbia,SRB
200,Europe & Central Asia,Upper middle income,Turkmenistan,TKM
199,Europe & Central Asia,Upper middle income,Türkiye,TUR
204,Europe & Central Asia,Upper middle income,Ukraine,UKR
7,Latin America & Caribbean,Upper middle income,Argentina,ARG
19,Latin America & Caribbean,Upper middle income,Belize,BLZ
26,Latin America & Caribbean,Upper middle income,Brazil,BRA
42,Latin America & Caribbean,Upper middle income,Colombia,COL
49,Latin America & Caribbean,Upper middle income,Cuba,CUB
55,Latin America & Caribbean,Upper middle income,Dominica,DMA
56,Latin America & Caribbean,Upper middle income,Dominican Republic,DOM
57,Latin America & Caribbean,Upper middle income,Ecuador,ECU
59,Latin America & Caribbean,Upper middle income,El Salvador,SLV
78,Latin America & Caribbean,Upper middle income,Grenada,GRD
80,Latin America & Caribbean,Upper middle income,Guatemala,GTM
97,Latin America & Caribbean,Upper middle income,Jamaica,JAM
127,Latin America & Caribbean,Upper middle income,Mexico,MEX
153,Latin America & Caribbean,Upper middle income,Paraguay,PRY
154,Latin America & Caribbean,Upper middle income,Peru,PER
182,Latin America & Caribbean,Upper middle income,St. Lucia,LCA
184,Latin America & Caribbean,Upper middle income,St. Vincent and the Grenadines,VCT
186,Latin America & Caribbean,Upper middle income,Suriname,SUR
2,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,Algeria,DZA
91,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,"Iran, Islamic Rep.",IRN
92,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,Iraq,IRQ
99,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,Jordan,JOR
113,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,Libya,LBY
121,South Asia,Upper middle income,Maldives,MDV
180,South Asia,Upper middle income,Sri Lanka,LKA
25,Sub-Saharan Africa,Upper middle income,Botswana,BWA
32,Sub-Saharan Africa,Upper middle income,Cabo Verde,CPV
60,Sub-Saharan Africa,Upper middle income,Equatorial Guinea,GNQ
70,Sub-Saharan Africa,Upper middle income,Gabon,GAB
126,Sub-Saharan Africa,Upper middle income,Mauritius,MUS
177,Sub-Saharan Africa,Upper middle income,South Africa,ZAF

In [83]:
pd.set_option("display.max_rows", None)

In [ ]:
# High income

candidate_pool[candidate_pool['Income group'] == 'High income'].sort_values(by=['Region','Economy'])[['Region','Income group','Economy','Code']]

# Countries selected: Japan, Spain, Barbados, Israel, United States

,Region,Income group,Economy,Code
3,East Asia & Pacific,High income,American Samoa,ASM
10,East Asia & Pacific,High income,Australia,AUS
28,East Asia & Pacific,High income,Brunei Darussalam,BRN
69,East Asia & Pacific,High income,French Polynesia,PYF
79,East Asia & Pacific,High income,Guam,GUM
86,East Asia & Pacific,High income,"Hong Kong SAR, China",HKG
98,East Asia & Pacific,High income,Japan,JPN
104,East Asia & Pacific,High income,"Korea, Rep.",KOR
117,East Asia & Pacific,High income,"Macao SAR, China",MAC
137,East Asia & Pacific,High income,Naoero,NRU
140,East Asia & Pacific,High income,New Caledonia,NCL
141,East Asia & Pacific,High income,New Zealand,NZL
146,East Asia & Pacific,High income,Northern Mariana Islands,MNP
150,East Asia & Pacific,High income,Palau,PLW
171,East Asia & Pacific,High income,Singapore,SGP
190,East Asia & Pacific,High income,"Taiwan, China",TWN
4,Europe & Central Asia,High income,Andorra,AND
11,Europe & Central Asia,High income,Austria,AUT
18,Europe & Central Asia,High income,Belgium,BEL
29,Europe & Central Asia,High income,Bulgaria,BGR
39,Europe & Central Asia,High income,Channel Islands,CHI
48,Europe & Central Asia,High income,Croatia,HRV
51,Europe & Central Asia,High income,Cyprus,CYP
52,Europe & Central Asia,High income,Czechia,CZE
53,Europe & Central Asia,High income,Denmark,DNK
62,Europe & Central Asia,High income,Estonia,EST
65,Europe & Central Asia,High income,Faroe Islands,FRO
67,Europe & Central Asia,High income,Finland,FIN
68,Europe & Central Asia,High income,France,FRA
73,Europe & Central Asia,High income,Germany,DEU
75,Europe & Central Asia,High income,Gibraltar,GIB
76,Europe & Central Asia,High income,Greece,GRC
77,Europe & Central Asia,High income,Greenland,GRL
87,Europe & Central Asia,High income,Hungary,HUN
88,Europe & Central Asia,High income,Iceland,ISL
93,Europe & Central Asia,High income,Ireland,IRL
94,Europe & Central Asia,High income,Isle of Man,IMN
96,Europe & Central Asia,High income,Italy,ITA
109,Europe & Central Asia,High income,Latvia,LVA
114,Europe & Central Asia,High income,Liechtenstein,LIE
115,Europe & Central Asia,High income,Lithuania,LTU
116,Europe & Central Asia,High income,Luxembourg,LUX
130,Europe & Central Asia,High income,Monaco,MCO
139,Europe & Central Asia,High income,Netherlands,NLD
147,Europe & Central Asia,High income,Norway,NOR
156,Europe & Central Asia,High income,Poland,POL
157,Europe & Central Asia,High income,Portugal,PRT
160,Europe & Central Asia,High income,Romania,ROU
161,Europe & Central Asia,High income,Russian Federation,RUS
164,Europe & Central Asia,High income,San Marino,SMR
173,Europe & Central Asia,High income,Slovak Republic,SVK
174,Europe & Central Asia,High income,Slovenia,SVN
179,Europe & Central Asia,High income,Spain,ESP
187,Europe & Central Asia,High income,Sweden,SWE
188,Europe & Central Asia,High income,Switzerland,CHE
206,Europe & Central Asia,High income,United Kingdom,GBR
6,Latin America & Caribbean,High income,Antigua and Barbuda,ATG
9,Latin America & Caribbean,High income,Aruba,ABW
13,Latin America & Caribbean,High income,"Bahamas, The",BHS
16,Latin America & Caribbean,High income,Barbados,BRB
27,Latin America & Caribbean,High income,British Virgin Islands,VGB
36,Latin America & Caribbean,High income,Cayman Islands,CYM
40,Latin America & Caribbean,High income,Chile,CHL
46,Latin America & Caribbean,High income,Costa Rica,CRI
50,Latin America & Caribbean,High income,Curaçao,CUW
83,Latin America & Caribbean,High income,Guyana,GUY
151,Latin America & Caribbean,High income,Panama,PAN
158,Latin America & Caribbean,High income,Puerto Rico (U.S.),PRI
172,Latin America & Caribbean,High income,Sint Maarten (Dutch part),SXM
181,Latin America & Caribbean,High income,St. Kitts and Nevis,KNA
183,Latin America & Caribbean,High income,St. Martin (French part),MAF
197,Latin America & Caribbean,High income,Trinidad and Tobago,TTO
201,Latin America & Caribbean,High income,Turks and Caicos Islands,TCA
208,Latin America & Caribbean,High income,Uruguay,URY
213,Latin America & Caribbean,High income,Virgin Islands (U.S.),VIR
14,"Middle East, North Africa, Afghanistan & Pakistan",High income,Bahrain,BHR
95,"Middle East, North Africa, Afghanistan & Pakistan",High income,Israel,ISR
106,"Middle East, North Africa, Afghanistan & Pakistan",High income,Kuwait,KWT
123,"Middle East, North Africa, Afghanistan & Pakistan",High income,Malta,MLT
148,"Middle East, North Africa, Afghanistan & Pakistan",High income,Oman,OMN
159,"Middle East, North Africa, Afghanistan & Pakistan",High income,Qatar,QAT
166,"Middle East, North Africa, Afghanistan & Pakistan",High income,Saudi Arabia,SAU
205,"Middle East, North Africa, Afghanistan & Pakistan",High income,United Arab Emirates,ARE
21,North America,High income,Bermuda,BMU
35,North America,High income,Canada,CAN
207,North America,High income,United States,USA
169,Sub-Saharan Africa,High income,Seychelles,SYC

## Candidate Country Screening Pool

Countries were first grouped using the World Bank income classifications:
Low Income, Lower Middle Income, Upper Middle Income, and High Income.

From each income group, countries were selected from different regions to
create geographic diversity in the sample. More countries were selected from
the low- and middle-income groups because the main focus of this project is
understanding digital infrastructure and access in developing economies.
High-income countries were included as a smaller comparison group.

The initial screening pool includes 29 countries:

- 8 Low Income
- 8 Lower Middle Income
- 8 Upper Middle Income
- 5 High Income

These are not the final countries that will be used in the analysis. The next
step is to check how much ITU data is available for each country between
2018 and 2025. Countries with too much missing data may need to be replaced
or removed from the final sample.