In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/raw/API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_367283.csv", skiprows=4)

In [4]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,99.900000,100.000000,100.000000,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN,NaN
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.700000,93.400000,97.700000,97.700000,97.700000,85.300000,85.300000,87.800000,NaN,NaN
3,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,48.902228,51.338199,51.289374,51.851866,54.366012,55.585594,57.064737,58.822166,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,42.900000,45.300000,45.600000,47.000000,48.200000,48.500000,51.100000,55.500000,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    265 non-null    object
 1   Country Code    265 non-null    object
 2   Indicator Name  265 non-null    object
 3   Indicator Code  265 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            107 non-null    float64
 35  1991            118 non-null    float64
 36  1992            135 non-null    float64
 37  1993            149 non-null    float64
 38  1994            155 non-null    float64
 39  1995            162 non-null    float64
 40  1996            174 non-null    float64
 41  1997            182 non-null    float64
 42  1998            191 non-null    float64
 43  1999            199 non-null    float64
 44  2000            258 non-null    float64
 45  2001            258 non-null    float64
 46  2002            259 non-null    float64
 47  2003            259 non-null    float64
 48  2004            259 non-null    float64
 49  2005            259 non-null    float64
 50  2006            259 non-null    float64
 51  2007            261 non-null    float64
 52  2008            261 non-null    float64
 53  2009            262 non-null    float64
 54  2010            262 non-null    float64
 55  2011            262 non-null    float64
 56  2012            262 non-null    float64
 57  2013            262 non-null    float64
 58  2014            262 non-null    float64
 59  2015            262 non-null    float64
 60  2016            262 non-null    float64
 61  2017            262 non-null    float64
 62  2018            262 non-null    float64
 63  2019            262 non-null    float64
 64  2020            262 non-null    float64
 65  2021            262 non-null    float64
 66  2022            262 non-null    float64
 67  2023            262 non-null    float64
 68  2024            262 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.1+ KB

In [9]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

In [10]:
df.shape

(265, 71)

## Creating a list of the selected countries to filter the electricity access data

In [11]:
selected_countries = [
    "Ethiopia",
    "Uganda",
    "Rwanda",
    "Congo, Dem. Rep.",
    "Burkina Faso",
    "Madagascar",
    "Afghanistan",
    "Yemen, Rep.",
    "Kenya",
    "Angola",
    "India",
    "Cambodia",
    "Morocco",
    "Honduras",
    "Kyrgyz Republic",
    "Papua New Guinea",
    "Colombia",
    "Jamaica",
    "Armenia",
    "Ukraine",
    "Indonesia",
    "Samoa",
    "Iraq",
    "Botswana",
    "Japan",
    "Spain",
    "Barbados",
    "Israel",
    "United States"
]

In [12]:
len(selected_countries)

29

In [15]:
electricity_candidates = df[df["Country Name"].isin(selected_countries)]

electricity_candidates

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
2,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.7,93.4,97.7,97.7,97.7,85.3,85.3,87.8,NaN,NaN
4,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,42.9,45.3,45.6,47.0,48.2,48.5,51.1,55.5,NaN,NaN
10,Armenia,ARM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.7,99.9,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
19,Burkina Faso,BFA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.0,14.4,17.6,18.5,19.0,19.5,21.7,34.0,NaN,NaN
30,Barbados,BRB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
33,Botswana,BWA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.4,68.3,70.1,71.8,73.7,75.9,76.0,80.2,NaN,NaN
43,"Congo, Dem. Rep.",COD,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.0,18.7,19.1,20.1,20.8,21.5,22.1,22.5,NaN,NaN
45,Colombia,COL,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,98.5,99.4,99.7,100.0,100.0,98.7,98.9,NaN,NaN
70,Spain,ESP,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
72,Ethiopia,ETH,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,44.3,44.8,48.0,51.1,54.2,55.0,55.4,56.6,NaN,NaN
96,Honduras,HND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.5,91.6,91.1,93.1,94.1,94.4,95.6,95.5,NaN,NaN
105,Indonesia,IDN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.1,98.5,98.8,97.0,99.2,100.0,99.4,99.9,NaN,NaN
108,India,IND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,91.8,95.7,95.9,96.5,99.6,99.2,99.5,99.9,NaN,NaN
112,Iraq,IRQ,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.9,99.9,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
114,Israel,ISR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
116,Jamaica,JAM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.4,98.2,98.9,99.7,100.0,100.0,97.7,97.7,NaN,NaN
118,Japan,JPN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
120,Kenya,KEN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,55.8,61.2,69.7,71.5,76.5,76.0,76.2,77.0,NaN,NaN
121,Kyrgyz Republic,KGZ,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,99.9,99.9,99.7,99.7,100.0,100.0,NaN,NaN
122,Cambodia,KHM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,89.1,80.7,84.0,86.4,82.5,92.3,95.0,99.2,NaN,NaN
147,Morocco,MAR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,98.1,99.6,100.0,100.0,100.0,100.0,100.0,NaN,NaN
150,Madagascar,MDG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.1,36.5,31.0,32.0,35.1,36.1,39.4,42.5,NaN,NaN
188,Papua New Guinea,PNG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.2,16.6,23.6,20.5,20.9,19.0,20.5,43.3,NaN,NaN
202,Rwanda,RWA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,34.1,38.0,46.6,45.2,48.7,50.6,63.9,72.0,NaN,NaN
246,Uganda,UGA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.4,41.9,41.3,42.1,45.2,47.1,51.5,55.3,NaN,NaN
247,Ukraine,UKR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
250,United States,USA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN
259,Samoa,WSM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,96.8,99.8,99.2,100.0,98.3,98.3,100.0,100.0,NaN,NaN
261,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,79.2,62.0,72.8,73.9,74.9,76.0,83.6,86.3,NaN,NaN

In [16]:
electricity_candidates.shape

(29, 71)

In [17]:
electricity_candidates.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 2 to 261
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    29 non-null     object
 1   Country Code    29 non-null     object
 2   Indicator Name  29 non-null     object
 3   Indicator Code  29 non-null     object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            8 non-null      float64
 35  1991            13 non-null     float64
 36  1992            16 non-null     float64
 37  1993            18 non-null     float64
 38  1994            19 non-null     float64
 39  1995            19 non-null     float64
 40  1996            20 non-null     float64
 41  1997            22 non-null     float64
 42  1998            23 non-null     float64
 43  1999            23 non-null     float64
 44  2000            29 non-null     float64
 45  2001            29 non-null     float64
 46  2002            29 non-null     float64
 47  2003            29 non-null     float64
 48  2004            29 non-null     float64
 49  2005            29 non-null     float64
 50  2006            29 non-null     float64
 51  2007            29 non-null     float64
 52  2008            29 non-null     float64
 53  2009            29 non-null     float64
 54  2010            29 non-null     float64
 55  2011            29 non-null     float64
 56  2012            29 non-null     float64
 57  2013            29 non-null     float64
 58  2014            29 non-null     float64
 59  2015            29 non-null     float64
 60  2016            29 non-null     float64
 61  2017            29 non-null     float64
 62  2018            29 non-null     float64
 63  2019            29 non-null     float64
 64  2020            29 non-null     float64
 65  2021            29 non-null     float64
 66  2022            29 non-null     float64
 67  2023            29 non-null     float64
 68  2024            29 non-null     float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 16.3+ KB

In [18]:
year_cols = [str(year) for year in range(2018, 2025)]

year_cols

['2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [19]:
id_cols = ["Country Name", "Country Code", "Indicator Name", "Indicator Code"]

In [20]:
id_cols + year_cols

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024']

In [21]:
## Combine the id_cols and year_cols to create a new dataframe with only the relevant columns

electricity_candidates = electricity_candidates[id_cols + year_cols]

In [22]:
electricity_candidates.shape

(29, 11)

In [23]:
electricity_candidates.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '2018', '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='object')

In [24]:
electric_selected = electricity_candidates.copy()

In [25]:
electric_selected.shape

(29, 11)

In [26]:
electric_selected.isna().sum()

Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
2018              0
2019              0
2020              0
2021              0
2022              0
2023              0
2024              0
dtype: int64

In [27]:
electric_selected[year_cols].describe()

,2018,2019,2020,2021,2022,2023,2024
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,75.931034,77.582759,78.058621,78.906897,79.117241,80.434483,82.900000
std,30.386970,29.418630,29.345765,28.685175,28.409821,27.259144,24.153068
min,14.400000,17.600000,18.500000,19.000000,19.000000,20.500000,22.500000
25%,45.300000,48.000000,51.100000,54.200000,55.000000,63.900000,72.000000
50%,95.700000,97.700000,97.000000,98.300000,98.300000,97.700000,98.900000
75%,99.900000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [36]:
electric_selected[['Country Name','2018', '2024']].sort_values(by='2018')

         Country Name   2018   2024
19       Burkina Faso   14.4   34.0
188  Papua New Guinea   16.6   43.3
43   Congo, Dem. Rep.   18.7   22.5
150        Madagascar   36.5   42.5
202            Rwanda   38.0   72.0
246            Uganda   41.9   55.3
72           Ethiopia   44.8   56.6
4              Angola   45.3   55.5
120             Kenya   61.2   77.0
261       Yemen, Rep.   62.0   86.3
33           Botswana   68.3   80.2
122          Cambodia   80.7   99.2
96           Honduras   91.6   95.5
2         Afghanistan   93.4   87.8
108             India   95.7   99.9
147           Morocco   98.1  100.0
116           Jamaica   98.2   97.7
105         Indonesia   98.5   99.9
45           Colombia   98.5   98.9
259             Samoa   99.8  100.0
10            Armenia   99.9  100.0
112              Iraq   99.9  100.0
118             Japan  100.0  100.0
121   Kyrgyz Republic  100.0  100.0
70              Spain  100.0  100.0
30           Barbados  100.0  100.0
247           Ukraine  100.0  100.0
250     United States  100.0  100.0
114            Israel  100.0  100.0