In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [100]:
# Loading ITU candidate data

df = pd.read_csv('../data/raw/itu_selected_candidates.csv')

df.shape

(9959, 15)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9959 entries, 0 to 9958
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SeriesID             9959 non-null   int64
 1   SeriesCode           9959 non-null   object
 2   Series               9959 non-null   object
 3   Unit                 9959 non-null   object
 4   Database             9959 non-null   object
 5   Year                 9959 non-null   int64
 6   AreaName             9959 non-null   object
 7   AreaCode             9959 non-null   object
 8   DisaggregationGroup  7726 non-null   object
 9   Disaggregation1      6970 non-null   object
 10  Disaggregation2      1480 non-null   object
 11  Value                9635 non-null   float64
 12  Notes                1935 non-null   object
 13  Source               8031 non-null   object
 14  LastModifiedOn       9959 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.1+ MB

In [102]:
df.columns

Index(['SeriesID', 'SeriesCode', 'Series', 'Unit', 'Database', 'Year',
       'AreaName', 'AreaCode', 'DisaggregationGroup', 'Disaggregation1',
       'Disaggregation2', 'Value', 'Notes', 'Source', 'LastModifiedOn'],
      dtype='object')

In [103]:
df.head()

,SeriesID,SeriesCode,Series,Unit,Database,Year,AreaName,AreaCode,DisaggregationGroup,Disaggregation1,Disaggregation2,Value,Notes,Source,LastModifiedOn
0,260,i61,Population,Value,ITU World Telecommunication Indicators Database,2025,Afghanistan,AFG,NaN,NaN,NaN,4.384411e+07,NaN,UN Population Division World Population Prospe...,2024-07-17
1,11630,i271s,Satellite broadband subscriptions,Value,ITU World Telecommunication Indicators Database,2025,Angola,AGO,Technology,Satellite broadband,NaN,8.970000e+02,NaN,Angolan Institute of Communications,2026-07-10
2,19257,i4213tfbb,Fixed-broadband subscriptions,Value,ITU World Telecommunication Indicators Database,2025,Angola,AGO,NaN,NaN,NaN,1.475280e+05,NaN,Angolan Institute of Communications,2026-07-10
3,19303,i992b,Fixed broadband subscriptions per 100 inhabitants,per 100 people,ITU World Telecommunication Indicators Database,2025,Angola,AGO,NaN,NaN,NaN,3.778890e-01,NaN,UN Population Division World Population Prospe...,2026-07-10
4,430,i271G,Percentage of the population covered by at lea...,% of individuals,ITU World Telecommunication Indicators Database,2025,Angola,AGO,NaN,NaN,NaN,9.087000e+01,NaN,Angolan Institute of Communications,2026-07-10

In [104]:
df["AreaName"].unique()

array(['Afghanistan', 'Angola', 'Armenia', 'Burkina Faso', 'Botswana',
       'Barbados', 'Cambodia', 'Colombia', 'Spain', 'Ethiopia',
       'Honduras', 'India', 'Indonesia', 'Iraq', 'Israel', 'Japan',
       'Jamaica', 'Kenya', 'Madagascar', 'Morocco', 'Papua New Guinea',
       'Rwanda', 'Samoa', 'Uganda', 'Ukraine', 'United States', 'Yemen',
       'Dem. Rep. of the Congo', 'Kyrgyzstan', 'Africa', 'The Americas',
       'Arab States', 'Asia & Pacific', 'Europe countries',
       'CIS countries', 'World',
       'Land Locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)',
       'Least Developed Countries (LDC)', 'High income', 'Low income',
       'Lower middle income', 'Upper middle income'], dtype=object)

In [105]:
## Checking for the exact names of the countries in the dataset to ensure that they match the names used in the World Bank data.
df[df["AreaName"].isin(['Dem. Rep. of the Congo', 'Kyrgystan'])][["AreaName",'AreaCode']].drop_duplicates()

                   AreaName AreaCode
851  Dem. Rep. of the Congo      COD

Candidate screening note: The Democratic Republic of the Congo and Kyrgyz Republic were removed from the candidate pool during data preparation due to cross-source naming/standardization issues. Because the initial country list was a screening pool rather than a predetermined final sample, resolving these inconsistencies was not necessary for the current analysis.

In [106]:
removed_countries = ['Dem. Rep. of the Congo', 'Kyrgystan']

df = df[~df["AreaName"].isin(removed_countries)].copy()

In [107]:
df[df["AreaName"].isin(removed_countries)].sum()

SeriesID                 0
SeriesCode               0
Series                   0
Unit                     0
Database                 0
Year                     0
AreaName                 0
AreaCode                 0
DisaggregationGroup      0
Disaggregation1          0
Disaggregation2          0
Value                  0.0
Notes                    0
Source                   0
LastModifiedOn           0
dtype: object

In [108]:
df["Series"].nunique()

125

In [109]:
df["Series"].unique()

array(['Population', 'Satellite broadband subscriptions ',
       'Fixed-broadband subscriptions',
       'Fixed broadband subscriptions per 100 inhabitants',
       'Percentage of the population covered by at least a 3G mobile network ',
       'Fibre-to-the-home/building Internet subscriptions ',
       'Terrestrial fixed wireless broadband subscriptions ',
       'Other fixed (wired)-broadband subscriptions ',
       'Percentage of the population covered by a mobile-cellular network ',
       'Percentage of the population covered by at least a 5G mobile network  ',
       'DSL Internet subscriptions',
       'Percentage of the population covered by at least an LTE/WiMAX mobile network.',
       'Data and voice mobile-broadband subscriptions',
       'Data-only mobile-broadband subscriptions',
       'Active mobile-broadband subscriptions ',
       'Active mobile-broadband subscriptions per 100 inhabitants',
       'Fixed broadband, 10 to 30 Mbit/s subscriptions per 100 inhabitants',
       'Fixed broadband, at least 100 Mbit/s subscriptions per 100 inhabitants',
       'Fixed broadband, 30 to 100 Mbit/s subscriptions per 100 inhabitants',
       'Fixed broadband, 2 Mbit/s to less than 10 Mbit/s subscriptions ',
       'Fixed broadband, 10 Mbit/s to less than 30 Mbit/s subscription',
       'Fixed broadband, equal to or above 10 Mbit/s subscriptions',
       'Fixed broadband,G10,% of total ',
       'Fixed broadband, 30 Mbit/s to less than 100 Mbit/s subscriptions',
       'Fixed broadband, 2 Mbit/s to less than 10 Mbit/s subscriptions per 100 inhabitants',
       'Fixed broadband,2to10,% of total ',
       'Fixed broadband, 256 kbit/s to less than 2 Mbit/s subscriptions per 100 inhabitants',
       'Fixed broadband, 30 Mbit/s to less than 100 Mbit/s subscriptions, % of total',
       'Fixed broadband, equal to or above 10 Mbit/s subscriptions per 100 inhabitants',
       'Cable modem Internet subscriptions ',
       '256to2Mbit/s subscriptions, as % of total fixed broadband subscriptions ',
       'Fixed broadband, 10 Mbit/s to less than 30 Mbit/s subscriptions, % of total',
       'Fixed broadband, equal to or above 100 Mbit/s subscriptions',
       'Fixed broadband, 256 kbit/s to less than 2 Mbit/s subscriptions ',
       'Fixed broadband, equal to or above 100 Mbit/s subscriptions, % of total',
       'Active subscriptions to LTE/WiMAX mobile-broadband networks',
       'Internet users (%)',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8 - FEMALE',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56',
       'HH07 - Individuals who used the internet (from any location) - %_POP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2 - MALE',
       'HH06 - Households with Internet access at home - %_HH - URBAN',
       'Estimated proportion of households with Internet access at home',
       'HH06 - Households with Internet access at home - %_HH - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15 - MALE',
       'Standard mobile-broadband subscriptions per 100 inhabitants',
       'Dedicated mobile data subscriptions per 100 inhabitants  ',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS'],
      dtype=object)

In [110]:
## Will located the exacat indicators that are relevant to the project and create a new dataframe with only those indicators.

df[df["Series"].str.contains("Fixed-broadband subscriptions")]["Series"].unique()

array(['Fixed-broadband subscriptions'], dtype=object)

In [111]:
#df[df["Series"].str.contains("Individuals using the Internet")]["Series"].unique()

df[df["Series"].str.contains("Internet", case=False)]["Series"].unique()

array(['Fibre-to-the-home/building Internet subscriptions ',
       'DSL Internet subscriptions',
       'Cable modem Internet subscriptions ', 'Internet users (%)',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO9',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8 - FEMALE',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO8',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO0',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED56',
       'HH07 - Individuals who used the internet (from any location) - %_POP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2',
       'HH07 - Individuals who used the internet (from any location) - %_POP - UNEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO1',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTLABOUR - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO7',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED2',
       'HH06 - Households with Internet access at home - %_HH - NOCHILDREN',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO6',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED01 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 15TO24 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO5',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - URBAN',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCED34 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO4',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - 25TO74',
       'HH06 - Households with Internet access at home - %_HH - CHILDREN - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - SELFEMP - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO3',
       'HH07 - Individuals who used the internet (from any location) - %_POP - PAIDEMP - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ISCO2 - MALE',
       'HH06 - Households with Internet access at home - %_HH - URBAN',
       'Estimated proportion of households with Internet access at home',
       'HH06 - Households with Internet access at home - %_HH - RURAL',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - ABOVE74 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15 - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - BELOW15 - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS - MALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS - FEMALE',
       'HH07 - Individuals who used the internet (from any location) - %_POP - NOTCLASS'],
      dtype=object)

In [112]:
df[df["Series"] == "Internet users (%)"][["Series","Unit","Year","AreaName","Value"]].head(10)

                  Series              Unit  Year      AreaName      Value
191   Internet users (%)  % of individuals  2025         Spain  96.306186
386   Internet users (%)  % of individuals  2025         India  70.000000
456   Internet users (%)  % of individuals  2025     Indonesia  77.632362
914   Internet users (%)  % of individuals  2024   Afghanistan  16.094999
946   Internet users (%)  % of individuals  2024        Angola  40.704800
1021  Internet users (%)  % of individuals  2024       Armenia  83.426207
1024  Internet users (%)  % of individuals  2024  Burkina Faso  28.252701
1087  Internet users (%)  % of individuals  2024      Botswana  57.459500
1145  Internet users (%)  % of individuals  2024      Barbados  70.364700
1151  Internet users (%)  % of individuals  2024      Cambodia  68.475304

In [113]:
#df[df["Series"].str.contains("Households with Internet access at home")]["Series"].unique()

df[df["Series"].str.contains("household", case=False) & ~df["Series"].str.startswith("HH06")]["Series"].unique()

array(['Estimated proportion of households with Internet access at home'],
      dtype=object)

In [114]:
df[df["Series"] == "Estimated proportion of households with Internet access at home"][
    ["Series", "Unit", "Year", "AreaName", "Value"]
].head(10)

,Series,Unit,Year,AreaName,Value
290,Estimated proportion of households with Intern...,% of households,2025,Spain,97.433525
407,Estimated proportion of households with Intern...,% of households,2025,India,86.300000
447,Estimated proportion of households with Intern...,% of households,2025,Indonesia,91.659877
919,Estimated proportion of households with Intern...,% of households,2024,Afghanistan,27.989760
929,Estimated proportion of households with Intern...,% of households,2024,Angola,55.628243
1006,Estimated proportion of households with Intern...,% of households,2024,Armenia,93.503357
1062,Estimated proportion of households with Intern...,% of households,2024,Botswana,68.926818
1143,Estimated proportion of households with Intern...,% of households,2024,Barbados,77.871496
1179,Estimated proportion of households with Intern...,% of households,2024,Cambodia,70.210426
1214,Estimated proportion of households with Intern...,% of households,2024,Colombia,65.648787

In [115]:
#df[df["Series"].str.contains("Population coverage, by mobile network technology")]["Series"].unique()
df[df["Series"].str.contains("covered", case=False)]["Series"].unique()

array(['Percentage of the population covered by at least a 3G mobile network ',
       'Percentage of the population covered by a mobile-cellular network ',
       'Percentage of the population covered by at least a 5G mobile network  ',
       'Percentage of the population covered by at least an LTE/WiMAX mobile network.'],
      dtype=object)

In [116]:
df[df["Series"].str.contains("Active mobile-broadband subscriptions")]["Series"].unique()

array(['Active mobile-broadband subscriptions ',
       'Active mobile-broadband subscriptions per 100 inhabitants'],
      dtype=object)

In [117]:
df[df["Series"].str.contains("Population")]["Series"].unique()

array(['Population'], dtype=object)

In [118]:
## Confirming Core Indicators for the project
core_indicators = [
    "Population",
    "Fixed-broadband subscriptions",
    "Active mobile-broadband subscriptions",
    "Internet users (%)",
    "Percentage of the population covered by at least an LTE/WiMAX mobile network.",
    "Estimated proportion of households with Internet access at home"
]

In [119]:
itu_core = df[df["Series"].isin(core_indicators)].copy()

In [120]:
itu_core.shape

(1224, 15)

In [121]:
itu_core.nunique()

SeriesID                  5
SeriesCode                5
Series                    5
Unit                      3
Database                  1
Year                      8
AreaName                 42
AreaCode                 42
DisaggregationGroup       1
Disaggregation1           0
Disaggregation2           0
Value                  1049
Notes                   116
Source                   86
LastModifiedOn          125
dtype: int64

In [122]:
itu_core["Series"].unique()

array(['Population', 'Fixed-broadband subscriptions',
       'Percentage of the population covered by at least an LTE/WiMAX mobile network.',
       'Internet users (%)',
       'Estimated proportion of households with Internet access at home'],
      dtype=object)

In [123]:
# Noticed white space in the series names for one of the indicators, will remove it to ensure consistency in the data.

df["Series"] = df["Series"].str.strip()

In [124]:
itu_core = df[df["Series"].isin(core_indicators)].copy()

In [125]:
itu_core.shape

(1431, 15)

In [126]:
itu_core["Series"].unique()

array(['Population', 'Fixed-broadband subscriptions',
       'Percentage of the population covered by at least an LTE/WiMAX mobile network.',
       'Active mobile-broadband subscriptions', 'Internet users (%)',
       'Estimated proportion of households with Internet access at home'],
      dtype=object)

In [127]:
itu_core["Series"].nunique()

6

In [128]:
df["AreaName"].unique()

array(['Afghanistan', 'Angola', 'Armenia', 'Burkina Faso', 'Botswana',
       'Barbados', 'Cambodia', 'Colombia', 'Spain', 'Ethiopia',
       'Honduras', 'India', 'Indonesia', 'Iraq', 'Israel', 'Japan',
       'Jamaica', 'Kenya', 'Madagascar', 'Morocco', 'Papua New Guinea',
       'Rwanda', 'Samoa', 'Uganda', 'Ukraine', 'United States', 'Yemen',
       'Kyrgyzstan', 'Africa', 'The Americas', 'Arab States',
       'Asia & Pacific', 'Europe countries', 'CIS countries', 'World',
       'Land Locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)',
       'Least Developed Countries (LDC)', 'High income', 'Low income',
       'Lower middle income', 'Upper middle income'], dtype=object)

In [129]:
itu_candidate_countries = ["Ethiopia",
    "Uganda",
    "Rwanda",
    "Burkina Faso",
    "Madagascar",
    "Afghanistan",
    "Yemen, Rep.",
    "Kenya",
    "Angola",
    "India",
    "Cambodia",
    "Morocco",
    "Honduras",
    "Papua New Guinea",
    "Colombia",
    "Jamaica",
    "Armenia",
    "Ukraine",
    "Indonesia",
    "Samoa",
    "Iraq",
    "Botswana",
    "Japan",
    "Spain",
    "Barbados",
    "Israel",
    "United States"]

In [130]:
itu_core["AreaName"].isin(itu_candidate_countries)

0        True
2        True
5        True
12       True
15       True
        ...
9928    False
9938    False
9945    False
9947    False
9954    False
Name: AreaName, Length: 1431, dtype: bool

In [131]:
itu_temp_selected = itu_core[itu_core["AreaName"].isin(itu_candidate_countries)].copy()

In [132]:
itu_temp_selected[["AreaName", "AreaCode"]].drop_duplicates

<bound method DataFrame.drop_duplicates of            AreaName AreaCode
0       Afghanistan      AFG
2            Angola      AGO
5            Angola      AGO
12           Angola      AGO
15           Angola      AGO
...             ...      ...
8766  United States      USA
8769  United States      USA
8778  United States      USA
8784  United States      USA
8788  United States      USA

[1135 rows x 2 columns]>

In [133]:
itu_temp_selected["AreaName"].unique()

array(['Afghanistan', 'Angola', 'Armenia', 'Burkina Faso', 'Botswana',
       'Barbados', 'Cambodia', 'Colombia', 'Spain', 'Ethiopia',
       'Honduras', 'India', 'Indonesia', 'Iraq', 'Israel', 'Japan',
       'Jamaica', 'Kenya', 'Madagascar', 'Morocco', 'Papua New Guinea',
       'Rwanda', 'Samoa', 'Uganda', 'Ukraine', 'United States'],
      dtype=object)

In [134]:
[country for country in itu_candidate_countries if country not in itu_core["AreaName"].unique()]

['Yemen, Rep.']

In [140]:
itu_core["AreaName"] = itu_core["AreaName"].replace({
    "Yemen": "Yemen, Rep."
})

In [141]:
itu_core["AreaName"].unique()

array(['Afghanistan', 'Angola', 'Armenia', 'Burkina Faso', 'Botswana',
       'Barbados', 'Cambodia', 'Colombia', 'Spain', 'Ethiopia',
       'Honduras', 'India', 'Indonesia', 'Iraq', 'Israel', 'Japan',
       'Jamaica', 'Kenya', 'Madagascar', 'Morocco', 'Papua New Guinea',
       'Rwanda', 'Samoa', 'Uganda', 'Ukraine', 'United States',
       'Yemen, Rep.', 'Kyrgyzstan', 'Africa', 'The Americas',
       'Arab States', 'Asia & Pacific', 'Europe countries',
       'CIS countries', 'World',
       'Land Locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)',
       'Least Developed Countries (LDC)', 'High income', 'Low income',
       'Lower middle income', 'Upper middle income'], dtype=object)

In [142]:
itu_temp_selected = itu_core[
    itu_core["AreaName"].isin(itu_candidate_countries)
].copy()

In [143]:
itu_temp_selected["AreaName"].unique()

array(['Afghanistan', 'Angola', 'Armenia', 'Burkina Faso', 'Botswana',
       'Barbados', 'Cambodia', 'Colombia', 'Spain', 'Ethiopia',
       'Honduras', 'India', 'Indonesia', 'Iraq', 'Israel', 'Japan',
       'Jamaica', 'Kenya', 'Madagascar', 'Morocco', 'Papua New Guinea',
       'Rwanda', 'Samoa', 'Uganda', 'Ukraine', 'United States',
       'Yemen, Rep.'], dtype=object)

In [144]:
itu_temp_selected["AreaName"].nunique()

27

In [145]:
itu_temp_selected["Year"].unique()

array([2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018], dtype=int64)

In [146]:
itu_temp_selected["Year"].nunique()

8